name: Go

on:
  push:
    branches: ["rc"]
    paths-ignore:
      - README.md
      - .gitignore
      #- .github/**
      - LICENSE

jobs:
  gettime:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ env.TIMESTAMP }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs: gettime
    env:
      GO_VERSION: "1.23.2"
      TIMESTAMP: ${{ needs.gettime.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make all-platforms

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/*
          if-no-files-found: error

  release:
    needs:
      - gettime
      - build
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ needs.gettime.outputs.timestamp }}
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: "./artifacts"
          if-no-files-found: error

      - name: Generate SHA512 checksums
        run: |
          cd artifacts
          find . -type f -name 'kthcloud*' -exec sha512sum {} + | sed 's|^\./||' > SHA512SUMS.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: release-${{ env.TIMESTAMP }}
          release_name: Release ${{ env.TIMESTAMP }}
          generate_release_notes: true
          files: artifacts/**/*

      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
