name: Go

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**
      - docs/*
      - LICENSE
      - license/**

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.24.3
    outputs:
      timestamp: ${{ env.TIMESTAMP }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    env:
      TIMESTAMP: ${{ needs.setup.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make release BINARY_NAME=kthcloud_${{ matrix.arch }}_${{ matrix.os }} BUILDTIMESTAMP=${{ env.TIMESTAMP }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}_${{ matrix.os }}_bins
          path: bin/*
          if-no-files-found: error

  licenses:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set GOPATH and PATH
        run: |
          export GOPATH=$HOME/go
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Generate
        run: |
          make licenses

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: licenses
          path: licenses/*
          if-no-files-found: error

  release:
    needs:
      - setup
      - build
      - licenses
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ needs.setup.outputs.timestamp }}
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: "./artifacts"
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: release-${{ env.TIMESTAMP }}
          release_name: Release ${{ env.TIMESTAMP }}
          generate_release_notes: true
          files: artifacts/**/*

      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
