name: RC

on:
  push:
    branches: ["rc"]
    paths-ignore:
      - README.md
      - .gitignore
      #- .github/**
      - LICENSE

jobs:
  gettime:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ env.TIMESTAMP }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs: gettime
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        go-version: ["1.23.2"]
    env:
      TIMESTAMP: ${{ needs.gettime.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make release BINARY_NAME=kthcloud_${{ matrix.arch }}_${{ matrix.os }} BUILDTIMESTAMP=${{ env.TIMESTAMP }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: bin/*
          if-no-files-found: error
