name: RC

on:
  push:
    branches: ["rc"]
    paths-ignore:
      - README.md
      - .gitignore
      #- .github/**
      - LICENSE

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.23.2
    outputs:
      timestamp: ${{ env.TIMESTAMP }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ env.GO_VERSION }}-

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: go mod download

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    env:
      TIMESTAMP: ${{ needs.setup.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make release BINARY_NAME=kthcloud_${{ matrix.arch }}_${{ matrix.os }} BUILDTIMESTAMP=${{ env.TIMESTAMP }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}_${{ matrix.os }}_bins
          path: bin/*
          if-no-files-found: error
